### ISSUE TITLE
No README

### ISSUE THREAD

**Issue by drrosa** [pwoolcoc/jupyter-rs#1]
Thanks for developing this kernel, I've been looking for it! But is it functional already? and would you mind explaining how to install it and get it to work with Jupyter?

**Comment by pwoolcoc** [comment]
thanks for opening this issue, and thanks for the interest! Unfortunately this is not functional right now. When installed properly, it listens on all the right ports, and can respond to `ping`s from the jupyter front-end, but that is about it right now. I have not abandoned it, I just don't get a lot of time to do development outside of work, so progress is slow.

I will leave this open until I get a README up, even if it is just a message about the current non-usefulness of the project :)

**Comment by rosatamsen** [comment]
Okay I see, thanks for replying promptly. Once you get a chance to work on the README you should also explain how to install it properly and include anything you think might help others contribute to this project.

**Comment by jeyraof** [comment]
Cheer up @pwoolcoc , :+1: 
I'm waiting too.

**Comment by pwoolcoc** [comment]
Ok, I have updated a few things and added a README with installation instructions for linux. I am going to try to get a bit more time to work on this, so hopefully I can pick up the pace, development-wise.

**Comment by xavier83** [comment]
Is it usable yet?

**Comment by xavier83** [comment]
Is this project alive?

**Comment by pwoolcoc** [comment]
I do intend on returning to it, but there is currently no movement on it.
