### ISSUE TITLE
zmq::Message error when I try to compile jupyter-rs

### ISSUE THREAD

**Issue by gardiac2002** [pwoolcoc/jupyter-rs#6]
Hello,

I am trying to compile `jupyter_rs`, but always run in the following error.

- System: Ubuntu 16.04
- Rust: rustc 1.25.0-nightly (3ec5a99aa 2018-02-14)
- Cargo: cargo 0.26.0-nightly (1d6dfea44 2018-01-26)

**Error**

> warning: unused `#[macro_use]` import
>  --> src/lib.rs:9:1
>   |
> 9 | #[macro_use] extern crate nom;
>   | ^^^^^^^^^^^^
>   |
>   = note: #[warn(unused_imports)] on by default
> 
> error[E0277]: the `?` operator can only be applied to values that implement `std::ops::Try`
>   --> src/message.rs:38:19
>    |
> 38 |     let mut msg = zmq::Message::new()?;
>    |                   ^^^^^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `zmq::Message`
>    |
>    = help: the trait `std::ops::Try` is not implemented for `zmq::Message`
>    = note: required by `std::ops::Try::into_result`
> 
> error[E0599]: no method named `unwrap` found for type `zmq::Message` in the current scope
>   --> src/heartbeat.rs:30:43
>    |
> 30 |         let mut msg = zmq::Message::new().unwrap();
>    |                                           ^^^^^^
> 
> warning: use of deprecated item 'zmq::Socket::send_str': Use `send` instead
>   --> src/heartbeat.rs:35:23
>    |
> 35 |             responder.send_str(recvd, 0).unwrap();
>    |                       ^^^^^^^^
>    |
>    = note: #[warn(deprecated)] on by default
> 
> error[E0599]: no method named `unwrap` found for type `zmq::Message` in the current scope
>   --> src/control.rs:30:43
>    |
> 30 |         let mut msg = zmq::Message::new().unwrap();
>    |                                           ^^^^^^
> 
> error: aborting due to 3 previous errors
> 
> error: Could not compile `jupyter-kernel`.
> 
> To learn more, run the command again with --verbose.

**Comment by pwoolcoc** [comment]
Thanks for the report! Unfortunately, this project has never actually been completed, so compile-timeand/or runtime failures are expected. Also, I'm not working on this branch anymore, I'm in the process of moving this over to a tokio backend, so I have no plans to fix the `master` branch as it currently stands. When I have the time to finish the tokio refactor, it will become the new `master` branch.
