### ISSUE TITLE
Is this woking?

### ISSUE THREAD

**Issue by arunkumar413** [pwoolcoc/jupyter-rs#7]
Does this kernel work with latest jupyter lab and also rust and is it being considered for active development?

**Comment by pwoolcoc** [comment]
No, sorry, I haven't been able to get back to this lately, it does not work. I'm hoping to get back to it soon but I have no idea if that will happen or not

**Comment by arunkumar413** [comment]
It's better to work with an express/node js localhost webapp than to work with jupyter. Node has better modules for communication with shell. The notebook like UI can be built easily using front end tech (html,jquery, css)

Jupyter uses some zeromq to communicate with shell and also it requires a kernel to be specifically built for it.
